CREATE SEQUENCE txn_id_seq
  MINVALUE 1
  MAXVALUE 99999999
  START WITH 1
  INCREMENT BY 1
;

CREATE TABLE KTransactions (
  txn_id NUMBER,
  sender_id NUMBER,
  recipient_id NUMBER,
  amount NUMBER,
  txn_date DATE,
  CONSTRAINT pk_ktransaction PRIMARY KEY (txn_id),
  CONSTRAINT fk_sender
    FOREIGN KEY (sender_id)
    REFERENCES Employees(emp_id),
  CONSTRAINT fk_recipient
    FOREIGN KEY (recipient_id)
    REFERENCES Employees(emp_id)
);

CREATE TABLE Employees (
  emp_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(64) NOT NULL,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(20) NOT NULL,
  email VARCHAR(20) UNIQUE NOT NULL,
  admin NUMBER(1) DEFAULT ON NULL 0,
  points_received NUMBER DEFAULT ON NULL 0,
  points_givable NUMBER DEFAULT ON NULL 0,
  CONSTRAINT pk_employees PRIMARY KEY (emp_id)
);

CREATE TRIGGER ktransactions_on_insert
  BEFORE INSERT ON Ktransactions
  FOR EACH ROW
BEGIN
  SELECT txn_id_seq.nextval
  INTO :new.txn_id
  FROM dual;
END;
